# Generated by Django 3.0.7 on 2021-08-17 16:24

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210817_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body_custom',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
