# Generated by Django 3.2.6 on 2021-08-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210817_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body_custom',
            field=models.JSONField(null=True),
        ),
    ]
