# Generated by Django 3.2.6 on 2021-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='postTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='NULL', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(to='posts.postTag'),
        ),
    ]
