# Generated by Django 3.2.6 on 2021-10-14 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211013_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 46, 50, 113729)),
        ),
    ]
