# Generated by Django 3.2.6 on 2021-10-15 09:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20211015_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(default='keder123@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='users.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 15, 1, 34, 782372)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 15, 1, 34, 781372)),
        ),
    ]
