# Generated by Django 3.0.7 on 2021-06-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic_path',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
