# Generated by Django 3.0.7 on 2021-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210624_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_pic_path',
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
