# Generated by Django 3.2.6 on 2021-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210624_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='bio',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='interests',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='ph_no',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
