# Generated by Django 3.2.6 on 2021-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210825_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='interests',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='ph_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
