# Generated by Django 3.2.6 on 2021-10-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210825_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='uploads/profile'),
        ),
    ]
