# Generated by Django 3.2.6 on 2021-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_register_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='register',
            name='profile_pic_name',
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
