# Generated by Django 3.2.6 on 2021-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211108_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic_url',
            field=models.CharField(default='https://res.cloudinary.com/dvcjj1k7a/image/upload/v1636390885/Blog/Profile/663328_ti7cnp.png', max_length=300, null=True),
        ),
    ]
